apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: skydish-auth-service:latest
          ports:
            - containerPort: 4000
          envFrom:
            - secretRef:
                name: skydish-secrets
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant-service
  template:
    metadata:
      labels:
        app: restaurant-service
    spec:
      containers:
        - name: restaurant-service
          image: skydish-restaurant-service:latest
          ports:
            - containerPort: 5002
          envFrom:
            - secretRef:
                name: skydish-secrets
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: skydish-order-service:latest
          ports:
            - containerPort: 5005
          envFrom:
            - secretRef:
                name: skydish-secrets
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery-service
  template:
    metadata:
      labels:
        app: delivery-service
    spec:
      containers:
        - name: delivery-service
          image: skydish-delivery-service:latest
          ports:
            - containerPort: 5003
          envFrom:
            - secretRef:
                name: skydish-secrets
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: skydish-payment-service:latest
          ports:
            - containerPort: 5004
          envFrom:
            - secretRef:
                name: skydish-secrets
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: skydish-frontend:latest
          ports:
            - containerPort: 3000
